allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - unrs-resolver
supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
